ItemList.push({name:"Sheet Music I",icon:[7,1],type:"song",cost:10000,elem:"FIRE",desc:"Sheet music for a piece titled \'Vigorous March\', which boosts the physical power of all allies while it plays.",skills:[["Song","Vigorous March"],["R:P_ATK","Motif: P DMG+10%"]]});
ItemList.push({name:"Sheet Music II",icon:[7,2],type:"song",cost:10000,elem:"WATER",desc:"Sheet music for a piece titled \'Spirit Song\', which boosts the magical power of all allies while it plays.",skills:[["Song","Spirit Song"],["R:PASSIVE","SPR+1 Deluxe"]]});
ItemList.push({name:"Sheet Music III",icon:[7,3],type:"song",cost:10000,elem:"EARTH",desc:"Sheet music for a piece titled \'Solid Sonata\', which boosts the physical resist of all allies while it plays.",skills:[["Song","Solid Sonata"],["R:P_DEF","Motif: P DMG-3%"]]});
ItemList.push({name:"Sheet Music IV",icon:[7,4],type:"song",cost:10000,elem:"THAUMA",desc:"Sheet music for a piece titled \'Runic Rhapsody\', which boosts the magical resist of all allies while it plays.",skills:[["Song","Runic Rhapsody"],["R:M_DEF","Motif: M DMG-3%"]]});
ItemList.push({name:"Sheet Music V",icon:[7,5],type:"song",cost:10000,elem:"WATER",desc:"Sheet music for a piece titled \'Mermaid\'s Melody\', which deals heavy damage to FIRE opponents when it\'s their turn.",skills:[["Song","Mermaid\'s Melody"],["R:PASSIVE","Motif: Nymph"]]});
ItemList.push({name:"Sheet Music VI",icon:[7,6],type:"song",cost:10000,elem:"DARK",desc:"Sheet music for a piece titled \'Dolorous Dirge\', which deals minor damage to opponents when it\'s their turn.",skills:[["Song","Dolorous Dirge"],["R:PASSIVE","Motif: Sirene Fatale"]]});
ItemList.push({name:"Sheet Music VII",icon:[7,7],type:"song",cost:10000,elem:"LIGHT",desc:"Sheet music for a piece titled \'Requiem\', which deals heavy damage to UNDEAD opponents when it\'s their turn.",skills:[["Song","Requiem"]]});
ItemList.push({name:"Sheet Music VIII",icon:[7,8],type:"song",cost:10000,elem:"LIGHT",desc:"Sheet music for a piece titled \'Ballad of Life\', which heals allies when it\'s their turn.",skills:[["Song","Ballad of Life"],["R:PASSIVE","Motif: Tenacious"]]});
ItemList.push({name:"Sheet Music IX",icon:[7,9],type:"song",cost:10000,elem:"AETHER",desc:"Sheet music for a piece titled \'Ballad of Balance\', which evenly splits damage across the side that was hit.\nThis Song is quite hard to play yet alone memorise even for a talented player.",skills:[["Song","Ballad of Balance"]]});
