ItemList.push({name:"Bronze Axe",type:"wepn",wpnType:"GREATAXE",atk:34,critical:2,hit:100,cost:500,hit_sfx:"slash_deep",desc:"A basic bronze greataxe.",skills:[["R:P_ATK","DMG+20%"]]});
ItemList.push({name:"Sun Axe",type:"wepn",wpnType:"GREATAXE",atk:36,critical:2,hit:100,cost:5000,hit_sfx:"slash_deep",desc:"A greataxe blessed by SOLAK, deity of Suns.",elem:"LIGHT",elemBonus:{DARK:1.25},skills:[["R:M_ATK","M DMG+20%"]]});
ItemList.push({name:"Iron Axe",type:"wepn",wpnType:"GREATAXE",atk:38,critical:2,hit:100,cost:4000,hit_sfx:"slash_deep",desc:"A greataxe made of... well, you can probably work it out somehow.",skills:[["R:P_ATK","Quarry: MAMMAL"],["R:M_ATK","Mark: MAMMAL"]]});
ItemList.push({name:"Bone Axe",type:"wepn",wpnType:"GREATAXE",atk:42,critical:2,hit:100,cost:1000,hit_sfx:"slash_deep",desc:"A primitive but effective axe, made from the thigh bone of a large beast and the pelvis-type thing of some probably different beast, maybe.",skills:[["Chief","Perforate"],["R:P_ATK","Quarry: MAMMAL"],["R:M_ATK","Mark: MAMMAL"]]});
ItemList.push({name:"Mighty Axe",type:"wepn",wpnType:"GREATAXE",atk:46,critical:2,hit:100,cost:9000,hit_sfx:"slash_deep",desc:"A solid, powerful axe made for rending armour.",skills:[["Chief","Barrier Break"],["R:P_ATK","Quarry: PEST"],["R:M_ATK","Mark: PEST"]]});
ItemList.push({name:"Stone Axe",type:"wepn",wpnType:"GREATAXE",atk:50,critical:2,hit:100,cost:10000,hit_sfx:"slash_deep",desc:"Though it may look very primitive, there\'s no denying the power of this axe!",skills:[["Chief","Dragon Rend"]]});
ItemList.push({name:"Silver Axe",type:"wepn",wpnType:"GREATAXE",atk:32,critical:2,hit:100,cost:12000,typeBonus:{UNDEAD:2,DEMON:2},elem:"LIGHT",hit_sfx:"slash_deep",desc:"A delicately ornate axe forged from the shiniest silver. Like all silver weapons, it\'s effective against undead.",skills:[["R:P_ATK","Quarry: UNDEAD"],["R:M_ATK","Mark: UNDEAD"]]});
ItemList.push({name:"Rending Eye",type:"wepn",wpnType:"GREATAXE",atk:45,critical:2,hit:100,cost:12000,elem:"EARTH",effects:[["R_ELEM","DARK",20],["SPR",4]],hit_sfx:"slash_deep",desc:"An axe shaped like the Eye of YALORT. It\'s designed for ceremonial purposes, but it still packs a whallop if used in real combat.",skills:[["R:P_ATK","Quarry: DREAM"],["R:M_ATK","Mark: DREAM"]]});
ItemList.push({name:"Drackal Crescent",type:"wepn",wpnType:"GREATAXE",atk:60,critical:5,hit:100,elem:"FIRE",typeBonus:{DRAGON:1.25},removestfx:{ALL_NULLS:66},cost:30000,effects:[["EMPOWER","DARK",20],["STR",5]],hit_sfx:"slash_deep",desc:"A powerful axe forged from Red Dragon Scales, traditionally used by the most powerful of Reptoid Chieftains.",skills:[["R:P_ATK","Quarry: MYTHICAL"],["R:M_ATK","Mark: MYTHICAL"]]});
