ItemList.push({name:"Mirrilixir",icon:[3,27],type:"item",cost:5000,action:["spell",{pow:0,SPR:15,elem:"LIGHT",stfx:{PSH:100,MSH:100},pfx:"shield"}],rgb:[220,220,220],pspray:{pfx:"sprayfall",DMG:null,stfx:{PSH:100,MSH:100},lasts:3,special:null},elem:"LIGHT",desc:"A potent potion with a silvery, reflective texture, like liquid mercury. Drinking it gives the imbiber P. Shield and M. Shield status effects."});
ItemList.push({name:"Speedy Juice",icon:[3,28],type:"item",cost:7500,action:["spell",{pow:0,SPR:15,elem:"AIR",stfx:{HST:100},pfx:"haste"}],rgb:[255,255,20],pspray:{pfx:"sprayfall",DMG:null,stfx:{HST:100},special:null},elem:"AIR",desc:"A great new energy drink from JuiceCorp! It gives you Haste, which grants you an additional turn placed with 70% of your AGL. No pressure but, this is the best status effect in the whole game, use this wisely!"});
ItemList.push({name:"Healthy Juice",icon:[3,29],type:"item",cost:2000,action:["spell",{pow:0,SPR:15,elem:"EARTH",stfx:{RGN:100},pfx:"regen"}],rgb:[255,255,255],pspray:{pfx:"sprayfall",DMG:null,stfx:{RGN:100},special:null},elem:"LIGHT",desc:"A great new energy drink from JuiceCorp! With this juice, you won\'t need medical attention ever again! It gives you Regen."});
ItemList.push({name:"Angry Juice",icon:[3,30],type:"item",cost:1500,action:["spell",{pow:0,SPR:15,elem:"FIRE",stfx:{BSK:100},pfx:"chakra"}],rgb:[200,0,0],pspray:{pfx:"sprayfall",DMG:null,stfx:{BSK:100},special:null},elem:"FIRE",desc:"A great new energy drink from JuiceCorp! This juice is great for letting out all that bottled-up torment! It puts you into a Berserk rage."});
ItemList.push({name:"Rainbow Juice",icon:[3,46],type:"item",cost:10000,action:["spell",{pow:0,SPR:15,elem:"LIGHT",stfx:{FN1:100,WN1:100,AN1:100,EN1:100,LN1:100,DN1:100,SN1:100,MN1:100},pfx:"rainbow"}],rgb:[180,255,20],pspray:{pfx:"sprayfall",DMG:null,stfx:{FN1:100,WN1:100,AN1:100,EN1:100,LN1:100,DN1:100,SN1:100,MN1:100},special:null},elem:"LIGHT",desc:"A special shaman\'s brew, which grants protection from a single attack of all eight elements."});
ItemList.push({name:"Prism Cocktail",icon:[3,47],type:"item",cost:10000,action:["spell",{pow:0,SPR:15,elem:"LIGHT",stfx:{SHF:100,SHA:100,SHE:100,SHW:100,SHL:100,SHD:100,SHS:100,SHM:100},pfx:"rainbow"}],rgb:[180,255,20],pspray:{pfx:"sprayfall",DMG:null,stfx:{ALL_SHELLS:100},special:null},elem:"LIGHT",desc:"Applies all eight Shells at once. After you drink this, anyone who so much as taps you on the shoulder will get absolutely obliterated."});
ItemList.push({name:"Noxious Bomb",icon:[3,40],type:"item",elem:"DARK",cost:1000,hurtful:true,action:["spell",{pow:0,mode:"S",SPR:20,elem:"DARK",stfx:{DRK:50,CNF:100,SLP:50,PSN:100},pfx:"smoke_vile"}],rgb:[160,140,40],desc:"A bomb filled with powdered chemicals, which explodes on impact. The resulting smoke induces Sleep, Confusion, Blindness and Poison."});
ItemList.push({name:"Zombie Juice",icon:[3,48],type:"item",cost:5000,elem:"DARK",hurtful:true,action:["spell",{pow:0,SPR:15,elem:"DARK",stfx:{ZOM:100},pfx:"zombify"}],rgb:[0,100,80],pspray:{pfx:"sprayfall",DMG:null,stfx:{ZOM:100},special:null},desc:"A terrible, cursed potion which makes any flesh it touches instantly necrotic, effectively turning a person into a zombie. Best used against foes, not friends."});
ItemList.push({name:"Oxyale",icon:[3,41],type:"item",cost:0,action:["add_status",["UWB"]],elem:"WATER",rgb:[0,200,255],desc:"A potent concoction that allows the drinker to breathe normally underwater for a time."});
