reactionInfo.M_ATK = [];
reactionInfo.M_ATK.push({skill:"M DMG+999999",effect:{dmgadd:999999},AP:-1,unmasterable:1,RP:0,elem:"THAUMA",desc:"Adds 999999 flat damage to your attack, as long as the target doesn\'t resist the element, it will be absolutely obliterated."});
reactionInfo.M_ATK.push({skill:"M DMG+400%",effect:{dmgmult:4},AP:-1,unmasterable:1,RP:0,elem:"THAUMA",desc:"Increases inflicted magical damage by 400%, effectively quintupling your damage."});
reactionInfo.M_ATK.push({skill:"Feeling Lucky?",effect:{accuracy:-50,critical:25},AP:-1,unmasterable:1,RP:0,elem:"EARTH",desc:"Are you interested in the ol\' game o\' chance? Equip this skill to receive a 25% Critical chance bonus, at the cost of 50% of your accuracy!"});
reactionInfo.M_ATK.push({skill:"Cursed Sight",effect:{stfx_inflict:{DRK:0.35,CRS:0.35}},unmasterable:1,AP:-1,RP:0,elem:"DARK",desc:"This reaction has a 35% chance of inflicting Blindness and/or Curse."});
reactionInfo.M_ATK.push({skill:"Adventurer Renown",effect:{typeBonus:{DRAGON:0.25,DEMON:0.25,GUARDIAN:0.25,ANNUNAKI:0.25}},AP:1,RP:0,elem:"FIRE",desc:"Social Fox is a master of fighting dragons, demons and all sorts of other monstrosities. \n\nHe gains a 25% damage boost to DEMON, DRAGON, GUARDIAN, and ANNUNAKI enemy types. This effect can stack with Mark: MYTHIC.",only:{LegendHero:true,UnLegend:true}});
reactionInfo.M_ATK.push({skill:"Sorceress\' Specialty",effect:{EMPOWER:{WATER:15}},AP:1,RP:0,elem:"WATER",desc:"Emela is a naturally gifted magician, capable of wielding many types of magic... However, her WATER magic in particular is mysteriously stronger than average.\n\nAdds 15% WATER empower to your magical damage.",only:{Elem:true,ElemCh3:true}});
reactionInfo.M_ATK.push({skill:"Jinx",effect:{stat_mod:{MDEF:1}},AP:10,RP:2,elem:"DARK",desc:"Bernard has mastered the art of magical trickery, getting your foe to look left while you hit them from the right. This reaction reduces MDEF by 1 each hit.",only:{BlMag:true}});
reactionInfo.M_ATK.push({skill:"Shadow Caster",effect:{accuracy:7,EMPOWER:{DARK:7}},AP:-1,unmasterable:1,RP:2,elem:"DARK",desc:"Sylvia\'s one with the darkness...She gains 7% accuracy and adds 7% empower to her DARK spells."});
reactionInfo.M_ATK.push({skill:"M NATURE+10%",effect:{EMPOWER:{FIRE:10,WATER:10,AIR:10,EARTH:10}},AP:5,RP:3,elem:"THAUMA",desc:"Adds 10% NATURAL empower to your magical damage.",only:{Shm:true}});
reactionInfo.M_ATK.push({skill:"M NATURE+20%",effect:{EMPOWER:{FIRE:20,WATER:20,AIR:20,EARTH:20}},AP:5,RP:5,elem:"THAUMA",desc:"Adds 20% NATURAL empower to your magical damage.",only:{Shm:true}});
reactionInfo.M_ATK.push({skill:"Meteorite Strike",effect:{stat_mod:{MDEF:1},dmgmult:0.01},AP:-1,unmasterable:1,RP:3,elem:"THAUMA",desc:"The way these Evening Stars were meticulously forged revealed some powerful traits within them.\nThis reaction reduces MDEF by 1. It also increases Magical damage by 1%, incredible."});
reactionInfo.M_ATK.push({skill:"M Corrosion",effect:{dmgadd:40,stfx_remove:{PSH:0.25,MSH:0.25}},AP:-1,RP:0,unmasterable:1,elem:"EARTH",desc:"Viper\'s Eye is a magical poison that can bypass certain defenses. This reaction adds quite a bit of additional damage to your attacks, with an additional 25% chance to dispel P. Shield and M. Shield."});
reactionInfo.M_ATK.push({skill:"M Bloodthirst 15%",effect:{drainHP:0.15,stfx_inflict:{BLD:0.15}},AP:-1,unmasterable:1,RP:0,elem:"DARK",desc:"Drains HP equal to 15% of magical damage dealt, with a 15% chance to inflict Bleed."});
reactionInfo.M_ATK.push({skill:"M Blood Drain 20%",displayname:"M Blood Drain 10%",effect:{drainHP:0.1,stfx_inflict:{BLD:0.1}},AP:-1,unmasterable:1,RP:0,elem:"DARK",desc:"As you use the Skull, the Skull uses you. Drains HP equal to 10% of damage dealt, as well as has a 10% chance to inflict Bleed."});
reactionInfo.M_ATK.push({skill:"M Skull Toxin 25%",effect:{stfx_inflict:{PSN:0.25}},AP:-1,unmasterable:1,RP:0,elem:"EARTH",desc:"The putrid foul Toxic Skull you picked up and then decided to equip has some use after all. This reaction has a 25% chance of inflicting Poison."});
reactionInfo.M_ATK.push({skill:"\'Lil Bit Off The Top",effect:{usingElemBonus:{DARK:0.07},drainHP:0.1},AP:-1,unmasterable:1,RP:4,elem:"DARK",desc:"Bernard\'s powers are a bit scary and honestly, a little creepy, too. This skill increases inflicted magical DARK damage by 7%, and drains HP equal to 10% of damage dealt."});
reactionInfo.M_ATK.push({skill:"M DMG+10%",effect:{dmgmult:0.1},AP:5,RP:2,elem:"THAUMA",desc:"Increases inflicted magical damage by 10%."});
reactionInfo.M_ATK.push({skill:"M DMG+20%",effect:{dmgmult:0.2},AP:10,RP:3,elem:"THAUMA",desc:"Increases inflicted magical damage by 20%."});
reactionInfo.M_ATK.push({skill:"M DMG+30%",effect:{dmgmult:0.3},AP:15,RP:5,elem:"THAUMA",desc:"Increases inflicted magical damage by 30%."});
reactionInfo.M_ATK.push({skill:"M DMG+40%",effect:{dmgmult:0.4},AP:20,RP:7,elem:"THAUMA",desc:"Increases inflicted magical damage by 40%."});
reactionInfo.M_ATK.push({skill:"M DMG+50%",effect:{dmgmult:0.5},AP:25,RP:9,only:{Hero:1},elem:"THAUMA",desc:"Increases inflicted magical damage by 50%."});
reactionInfo.M_ATK.push({skill:"M Accuracy+25%",effect:{accuracy:25},AP:10,RP:2,elem:"AIR",desc:"Increases the chance of scoring a hit by 25%."});
reactionInfo.M_ATK.push({skill:"M Critical+5%",effect:{critical:5},AP:5,RP:1,elem:"AIR",desc:"Increases the chance of scoring a magical critical hit by a flat 5%."});
reactionInfo.M_ATK.push({skill:"M Critical+10%",effect:{critical:10},AP:-1,unmasterable:1,RP:2,elem:"AIR",desc:"Increases the chance of scoring a magical critical hit by a flat 10%."});
reactionInfo.M_ATK.push({skill:"M Critical+15%",effect:{critical:15},AP:-1,unmasterable:1,RP:3,elem:"AIR",desc:"Increases the chance of scoring a magical critical hit by a flat 15%."});
reactionInfo.M_ATK.push({skill:"M FIRE+10%",effect:{usingElemBonus:{FIRE:0.1}},AP:5,RP:2,elem:"FIRE",desc:"Increases inflicted magical FIRE damage by 10%."});
reactionInfo.M_ATK.push({skill:"M FIRE+20%",effect:{usingElemBonus:{FIRE:0.2}},AP:10,RP:4,elem:"FIRE",desc:"Increases inflicted magical FIRE damage by 20%."});
reactionInfo.M_ATK.push({skill:"M WATER+20%",effect:{usingElemBonus:{WATER:0.2}},AP:10,RP:4,elem:"WATER",desc:"Increases inflicted magical WATER damage by 20%."});
reactionInfo.M_ATK.push({skill:"M EARTH+10%",effect:{usingElemBonus:{EARTH:0.1}},AP:5,RP:2,elem:"EARTH",desc:"Increases inflicted magical EARTH damage by 10%."});
reactionInfo.M_ATK.push({skill:"M EARTH+20%",effect:{usingElemBonus:{EARTH:0.2}},AP:10,RP:4,elem:"EARTH",desc:"Increases inflicted magical EARTH damage by 20%."});
reactionInfo.M_ATK.push({skill:"M AIR+10%",effect:{usingElemBonus:{AIR:0.1}},AP:5,RP:2,elem:"AIR",desc:"Increases inflicted magical AIR damage by 10%."});
reactionInfo.M_ATK.push({skill:"M AIR+20%",effect:{usingElemBonus:{AIR:0.2}},AP:10,RP:4,elem:"AIR",desc:"Increases inflicted magical AIR damage by 20%."});
reactionInfo.M_ATK.push({skill:"M LIGHT+10%",effect:{usingElemBonus:{LIGHT:0.1}},AP:5,RP:2,elem:"LIGHT",desc:"Increases inflicted magical LIGHT damage by 10%."});
reactionInfo.M_ATK.push({skill:"M LIGHT+20%",effect:{usingElemBonus:{LIGHT:0.2}},AP:10,RP:4,elem:"LIGHT",desc:"Increases inflicted magical LIGHT damage by 20%."});
reactionInfo.M_ATK.push({skill:"M DARK+20%",effect:{usingElemBonus:{DARK:0.2}},AP:10,RP:4,elem:"DARK",desc:"Increases inflicted magical DARK damage by 20%."});
reactionInfo.M_ATK.push({skill:"M THAUMA+10%",effect:{EMPOWER:{THAUMA:0.1}},AP:-1,unmasterable:1,RP:1,elem:"THAUMA",desc:"Adds 10% THAUMA empower to your magical damage."});
reactionInfo.M_ATK.push({skill:"M THAUMA+20%",effect:{EMPOWER:{THAUMA:0.2}},AP:-1,unmasterable:1,RP:3,elem:"THAUMA",desc:"Adds 20% THAUMA empower to your magical damage."});
reactionInfo.M_ATK.push({skill:"M THAUMA+30%",effect:{EMPOWER:{THAUMA:0.3}},AP:-1,unmasterable:1,RP:4,elem:"THAUMA",desc:"Adds 30% THAUMA empower to your magical damage."});
reactionInfo.M_ATK.push({skill:"M+Poison 25%",effect:{stfx_inflict:{PSN:0.25}},AP:10,RP:3,elem:"EARTH",desc:"This reaction has a 25% chance of inflicting Poison."});
reactionInfo.M_ATK.push({skill:"M+Stun 25%",displayname:"M+Paralysis 25%",effect:{stfx_inflict:{PAR:0.25}},AP:10,RP:3,elem:"AIR",desc:"This reaction has a 25% chance of inflicting Paralysis."});
reactionInfo.M_ATK.push({skill:"M+Numb 25%",effect:{stfx_inflict:{NUM:0.25}},AP:10,RP:3,elem:"FIRE",desc:"This reaction has a 25% chance of inflicting Numbness."});
reactionInfo.M_ATK.push({skill:"M+Silence 25%",effect:{stfx_inflict:{SIL:0.25}},AP:10,RP:3,elem:"THAUMA",desc:"This reaction has a 25% chance of inflicting Silence."});
reactionInfo.M_ATK.push({skill:"M+Curse 25%",effect:{stfx_inflict:{CRS:0.25}},AP:10,RP:3,elem:"DARK",desc:"This reaction has a 25% chance of inflicting Curse."});
reactionInfo.M_ATK.push({skill:"M+Confuse 25%",effect:{stfx_inflict:{CNF:0.25}},AP:10,RP:3,elem:"FIG",desc:"This reaction has a 25% chance of inflicting Confusion."});
reactionInfo.M_ATK.push({skill:"M+Sleep 25%",effect:{stfx_inflict:{SLP:0.25}},AP:10,RP:3,elem:"AIR",desc:"This reaction has a 25% chance of inflicting Sleep."});
reactionInfo.M_ATK.push({skill:"M+Blind 25%",effect:{stfx_inflict:{DRK:0.25}},AP:10,RP:3,elem:"DARK",desc:"This reaction has a 25% chance of inflicting Blindness."});
reactionInfo.M_ATK.push({skill:"M+Bleed 25%",effect:{stfx_inflict:{BLD:0.25}},AP:10,RP:3,elem:"DARK",desc:"This reaction has a 25% chance of inflicting Bleed."});
reactionInfo.M_ATK.push({skill:"M. Shield Break 25%",effect:{stfx_remove:{MSH:0.25}},AP:5,RP:3,elem:"DARK",desc:"This reaction has a 25% chance of removing the M. Shield status."});
reactionInfo.M_ATK.push({skill:"M Drain HP 10%",effect:{drainHP:0.1},AP:5,RP:4,elem:"DARK",desc:"Drains HP equal to 10% of damage dealt."});
reactionInfo.M_ATK.push({skill:"M Drain HP 20%",effect:{drainHP:0.2},AP:10,RP:6,elem:"DARK",desc:"Drains HP equal to 20% of damage dealt."});
reactionInfo.M_ATK.push({skill:"M Drain HP 30%",effect:{drainHP:0.3},AP:15,RP:8,elem:"DARK",desc:"Drains HP equal to 30% of damage dealt."});
reactionInfo.M_ATK.push({skill:"Mark: UNDEAD",effect:{typeBonus:{UNDEAD:0.25}},AP:5,RP:4,elem:"LIGHT",desc:"Increases magical damage by 25% against the UNDEAD enemy type."});
reactionInfo.M_ATK.push({skill:"Mark: ARTIFICIAL",effect:{typeBonus:{CONSTRUCT:0.25,ILLUSION:0.25,CRYSTAL:0.25,ELEMENTAL:0.25}},AP:5,RP:3,elem:"THAUMA",desc:"Increases magical damage by 25% against CONSTRUCT, ILLUSION, CRYSTAL, and ELEMENTAL enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: AQUATIC",effect:{typeBonus:{ICHTHYD:0.25,ABERRATION:0.25,OOZE:0.25}},AP:5,RP:3,elem:"WATER",desc:"Increases magical damage by 25% against ICHTHYD, ABERRATION, and OOZE enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: REPTILE",effect:{typeBonus:{REPTILIAN:0.25,REPTOID:0.25}},AP:5,RP:2,elem:"AIR",desc:"Increases magical damage by 25% against REPTILIAN and REPTOID enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: MYTHICAL",displayname:"Mark: MYTHIC",effect:{typeBonus:{DRAGON:0.25,DEMON:0.25,GUARDIAN:0.25,ANNUNAKI:0.25}},AP:5,RP:3,elem:"LIGHT",desc:"Increases magical damage by 25% against DRAGON, DEMON, GUARDIAN, and ANNUNAKI enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: MAMMAL",effect:{typeBonus:{HUMAN:0.25,BEAST:0.25,MAGICAL_BEAST:0.25,GOBLINOID:0.25}},AP:5,RP:3,elem:"DARK",desc:"Increases magical damage by 25% against HUMAN, BEAST, MAGICAL BEAST, and GOBLINOID enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: PEST",effect:{typeBonus:{INSECT:0.25,AERIAL:0.25,PLANTOID:0.25,FEY:0.25}},AP:5,RP:3,elem:"AIR",desc:"Increases magical damage by 25% against INSECT, AERIAL, PLANTOID, and FEY enemy types."});
reactionInfo.M_ATK.push({skill:"Mark: DREAM",effect:{typeBonus:{FIGMENT:0.25,SPIRIT:0.25}},AP:5,RP:3,elem:"FIG",desc:"Increases magical damage by 25% against FIGMENT and SPIRIT enemy types."});
